### ISSUE TITLE
Updated to "latest" version and now cannot access the GUI.

### ISSUE THREAD

**Issue by shulist** [MekayelAnik/ispyagentdvr-docker#36]
The tail of the log file states 

`Failed to create secure directory (/root/.config/pulse): Permission denied` 

And while the graphic for the opening of  AgentDVR comes up you cannot do anything on the opening screen. Buttons which work are `Account Menu`, `Help`, `Full Screen`. All others are greyed out. 

Clearing the browser cache does nothing and using any other browser ends up with the same result.

I've tried to use the "stable" version with the same result. Here's my compose file:

```
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - AGENTDVR_WEBUI_PORT=8090 
      - TZ=America/Toronto
    volumes:
      - /mnt/video/config:/AgentDVR/Media/XML
      - /mnt/video/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /mnt/video/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50100:50000-50100/udp
    restart: unless-stopped
```
Any suggestions or help will be appreciated.

**Comment by shulist** [comment]
Ok I rolled back to the original image I had  which was 5.1.6.0 and found all was back except I was unable to bulk delete any recordings. I backed that versions config up and upgraded to 5.8.0.0 and while it again worked there is still some sort of defect in bulk deleting recordings. 

Any suggestions?

**Comment by ispysoftware** [comment]
Look at your reddit question

**Comment by suazojaime** [comment]
What was the solution for this issue? what reddit question is being referenced? 
I'm having the same issue.

**Comment by bartlebi** [comment]
I think the problem is actual. Exactly the same problem after updating to the latest version. What's strange is that after updating the image everything worked without problems for some time, but after a day access became impossible. At the same time, there are no logs inside the container to analyze the situation.

**Comment by MekayelAnik** [comment]
The problem is not from Pulse audio. The problem is occuring from Turn server.
For the time being please use MACVLAN to deploy the container or use the last working version till the problem is resolved.

It should work on MACVLAN.

I will get back to you when the problem is resolved.

**Comment by shulist** [comment]
So a bit of an update on the "bulk delete" problem. And this is weird! The bulk delete problem is the same on a Win10 box (BoxF) using ANY browser. 

However, I also have a Linux box (BoxG) in my workshop also using Firefox and from that I  was able to bulk delete, furthermore I was also able to bulk delete on another Win10 box (BoxT) that is located in another property.

I am now thinking that the Win10 box has got some weird issue with the browser functions (Maybe something with MD or AVG that this device runs) at any rate I now think it is NOT related to Docker image. I am now trying to determine the differences between BoxF and BoxT - and with Windows this is not a simple task.

**Comment by xoxfaby** [comment]
```yaml
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:stable
    container_name: ispyagentdvr
    environment:
      - PUID=999
      - PGID=10000
      - TZ=Europe/Berlin
      - AGENTDVR_WEBUI_PORT=8090
    volumes:
      - /mnt/config/agentdvr:/AgentDVR/Media/XML
      - /mnt/Cameras:/AgentDVR/Media/WebServerRoot/Media
      - /mnt/config/agentdvr/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50100:50000-50100/udp
    restart: unless-stopped
    networks:
      macvlan_agentdvr:
        ipv4_address: 192.168.1.26
networks:
  macvlan_agentdvr:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/23
        ip_range: 192.168.0.0/23
        gateway: 192.168.0.138
```

One thing I'll actually note is that I'm not sure why this image won't use any UID under 1000? but it says it runs under root instead, i don't see how that could cause the problem

**Comment by MekayelAnik** [comment]
@xoxfaby 
1. Give a MAC address to the container. Otherwise the gateway won't be able to attach the IP to your container. Gateway/Router identifies by MAC address. If this doesn't solve your problem then,
2. Kindly remove all the previous config from the host `/mnt/config/agentdvr`

I have modified the docker compose file for you, try this. If there is a problem with this MAC address, generate a valid MAC address using a online MAC address generator. One more thing PGID and PUID should be the same as this runs the container as a user.

```
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:stable
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - AGENTDVR_WEBUI_PORT=8090
    volumes:
      - /mnt/config/agentdvr:/AgentDVR/Media/XML
      - /mnt/Cameras:/AgentDVR/Media/WebServerRoot/Media
      - /mnt/config/agentdvr/commands:/AgentDVR/Commands
    restart: unless-stopped
    hostname: ispyagentdvr
    domainname: local
    mac_address: AB-BC-C0-D1-E2-EC
    networks:
      macvlan_agentdvr:
        ipv4_address: 192.168.1.26
networks:
  macvlan_agentdvr:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/23
        ip_range: 192.168.0.0/23
        gateway: 192.168.0.138
```
Then on the client pc, make sure you are able to ping the container on `192.168.1.26`

Note: MACVLAN IP addresses can't be accessed from the host pc (on which the container have been deployed). So try another pc or mobile.

**Comment by xoxfaby** [comment]
I'm fairly certain if you don't specify a mac address, a random one will be used?
Also about the PUID thing, it still doesn't explain why you have limited it to only work above 1000?

**Comment by MekayelAnik** [comment]
> I'm fairly certain if you don't specify a mac address, a random one will be used? Also about the PUID thing, it still doesn't explain why you have limited it to only work above 1000?

I have limited the use of PUID above 1000, cause by default the LINUX uses <1000 to assign it to internal process (this is the best practice also) and 1000< for Users. 
To maintain the best practice, this was set to above 1000.

I am using MACVLAN to deploy AgentDVR, I can't reproduce your problem. So if you are still facing the problem, kindly post with some kind of logs with which we can work with.

**Comment by xoxfaby** [comment]
My understand was that 500-999 is commonly used for services, and that is what I see the stuff I run in docker as. But maybe I should change to 1000+. 

As for the macvlan problem, I believe it is due to my setup, where macvlan doesn't work on bridged interfaces, I'm still looking into how I can get around that.

**Comment by MekayelAnik** [comment]
The problem has been resolved for **MACVLAN**, **HOST** as well as **BRIDGE** type docker networks. Tested on `ispyagentdvr v6.3.3.0`
